model_name: "PUNN"
device: "cuda"
opt: "Adam"
criterion: "MSE"
storage: "journal"
search_space:
  n_hidden_neurons: [16, 64]
  n_hidden_layers: [2, 5]
  activation_function: ["relu", "tanh", "leaky_relu", "softplus"]
  epochs: [1000, 3000]
  patience: [200, 500]
  batch_size: [256, 512, 1400]
  lr: [0.0001, 0.01]